name: Python Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"] # Specify python versions to test against

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib requests plaid-python google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client openai
        # If you have a requirements.txt, you can use:
        # pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover -v
        # The -v flag provides verbose output.
        # The default discovery pattern is 'test*.py'.
        # If your test files are in a subdirectory (e.g., 'tests/'), use:
        # python -m unittest discover -s tests -v
